-- AlterTable
ALTER TABLE `user` MODIFY `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `inactive_date` DATETIME(6) NULL,
    MODIFY `social_type` VARCHAR(10) NOT NULL DEFAULT 'email',
    MODIFY `status` VARCHAR(15) NOT NULL DEFAULT 'active',
    MODIFY `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
